name: ChatPerWorld Lite
version: 1.0.0
description: ChatPerWorld Lite
author: penguin.niisan
website: https://github.com/penguinniisan/ChatPerWorldLite

main: com.penpennetworks.minecraft.chatperworldlite.ChatPerWorldLiteCore
database: false
